language: android
jdk: oraclejdk8

sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19


script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  # Build
  - ./gradlew build
  # Wait for the emulator
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &
  # Run the tests
  - ./gradlew connectedCheck

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

env:
  global:
    - ADB_INSTALL_TIMEOUT=8
    - DX_HEAP_SIZE=2048

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)
