language: android
jdk: oraclejdk8

sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.0
    - android-24
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19
  licenses:
    - 'android-sdk-license-.+'

env:
  global:
    - ADB_INSTALL_TIMEOUT=10
    - DX_HEAP_SIZE=2048

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window -gpu off -no-boot-anim &

script:
  - ./gradlew build jacocoTestReport --continue --stacktrace
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
  - ./gradlew connectedCheck --continue --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - wget http://imgur.com/tools/imgurbash.sh
  - chmod a+x imgurbash.sh
  - adb shell screencap -p | sed 's/\r$//' > screen.png
  - ./imgurbash.sh screen.png
