//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.03 at 06:37:20 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bnorm.com/barkeep/server/msg/xml/v2")
package com.bnorm.barkeep.server.msg.xml.v2;
